Adding functionality to cordon the node before destroying it.
kubernetes/autoscaler pull request #3649
Opened 2020-10-28 06:42 UTC by atulaggarwal

This helps load balancer to remove the node from healthy hosts (ALB does have this support).

This won't fix the issue of 502 completely as there is some time node to live even after cordoning as to serve In-Flight request.
Shamelessly copied from https://github.com/kubernetes/autoscaler/pull/3014/files

2020-10-28 06:51 UTC, atulaggarwal commented
Signed now

2020-10-31 15:22 UTC, atulaggarwal commented
Can someone review the PR and let me know if this kind of change make sense in autoscaler?

2020-11-03 17:00 UTC, MaciekPytel commented
FWIW I still believe the right solution is to make ingress controller aware of autoscaler taint (ex. [ingress-gce](https://github.com/kubernetes/ingress-gce/issues/595)). spec.Unschedulable has the problem of not having a clear owner, though the idea of pairing it with a taint as implemented in here somewhat mitigates this issue.

At a glance I'm not sure why we need 2 separate taints? Why not just skip default tainting logic and apply the ToBeDeletedTaint in cordoning logic? Having 2 separate writes on the node is a big downside as mutating api-server calls can be a big bottleneck when trying to scale-down large cluster rapidly.

I'm focusing on preparing patch releases now, I can do a more detailed review later this week.

2020-11-04 06:01 UTC, atulaggarwal commented
Thanks for the brief review. 
1. I am raising PR with aws lonader balancer to handle the taint.
2. I agree we should consolidate the taints at one place. I will work on it and make the changes. I still believe we should use spec.Unschedulable also so that standard implementatio unaware of autoscaler could listen for it.

2020-12-09 04:15 UTC, atulaggarwal commented
@MaciekPytel - Can you review the PR once and let me know if everything looks fine?

2021-01-11 21:26 UTC, ltagliamonte-dd commented
Folks why aren't we working on this? Can someone from the admin review?
this could easily solve a huge problem for tons of users.

2021-01-12 01:59 UTC, feiskyer reviewed
I'm +1 for adding this
/approve

2021-01-12 16:59 UTC, ltagliamonte-dd commented
@feiskyer thank you for the review and the approval.
What are the remaining step to see this upstream and released?

2021-01-13 23:45 UTC, ltagliamonte-dd commented
@Jeffwan do you mind review this PR as well?

2021-01-14 01:34 UTC, mwielgus requested changes

2021-01-14 01:34 UTC, mwielgus commented on cluster-autoscaler/utils/deletetaint/delete.go
> +			klog.V(1).Infof("Successfully uncordoned node %v by Cluster Autoscaler", freshNode.Name)
Given that the update has not yet happened this message is premature.

2021-01-14 01:34 UTC, mwielgus commented on cluster-autoscaler/main.go
> +	cordonNodeBeforeTerminate          = flag.Bool("cordon-node-before-terminating", true, "Should CA cordon nodes before terminating during downscale process")
Please launch new features initially disabled.

2021-01-14 01:34 UTC, mwielgus commented on cluster-autoscaler/utils/deletetaint/delete.go
> +		klog.V(1).Infof("Successfully cordoned node %v by Cluster Autoscaler", node.Name)
The update has not yet completed. The message is premature.

2021-01-14 02:30 UTC, atulaggarwal commented
@mwielgus - Thanks for reviewing the PR. I have made the changes as per the review comments. Please review it once more.

2021-01-14 10:52 UTC, mwielgus commented
Please squash commits to just 1.

2021-01-14 11:56 UTC, atulaggarwal commented
@mwielgus - Done

2021-01-14 12:17 UTC, mwielgus approved these changes
/lgtm
/approve

2021-01-14 12:19 UTC, merged

2021-01-14 12:20 UTC, MaciekPytel commented
For future reference - there is a growing number of request for CA to take additional custom actions as part of the drain (ex. https://github.com/kubernetes/autoscaler/pull/3792) and I'd like to propose extracting drain logic into processor as a long-term solution.
This will keep any additional logic encapsulated and make it so that no code related to opt-in features will be executed if those features are disabled (which should make it easier to merge any such changes as any regression risk is limited to users who opt-in).

2021-01-14 14:32 UTC, ltagliamonte commented
@mwielgus @feiskyer thank you for looking into this.
When can we expect a docker release?

2021-01-14 19:49 UTC, Jeffwan commented
> @mwielgus @feiskyer thank you for looking into this.
> When can we expect a docker release?

There's a release cycle, you will need to cherry-pick this merge to branches and next release will pick them up. 
At the same time, you can build your own image to use and don't need to wait for official release if you want it immediately.

2021-01-14 20:40 UTC, ltagliamonte-dd commented
@Jeffwan thank you for getting back to me, may you please tell me when the next release cycle is going to happen?

2021-02-10 18:45 UTC, spanky-medal commented
Does this PR resolve the issue found in https://github.com/kubernetes/autoscaler/issues/2045? I'm not clear following this thread from https://github.com/kubernetes/autoscaler/pull/3792

2021-02-11 02:05 UTC, atulaggarwal commented
I don't think this would solve issue #2045. This PR justs add UnSchedulable label to node being evicted so that it could be removed from load balancer. It would not change any way scheduling of pods before deleting the node.

2021-02-22 17:21 UTC, ltagliamonte-dd commented
@Jeffwan i've created a dev docker release for my staging testing, still waiting on the official release for prod.
Do you know when it is going to happen? i'm waiting for a release on  k8s 1.18.
Thanks

2021-03-01 07:51 UTC, infa-ddeore commented
@atulaggarwal I want to build a docker image for k8 `1.5`, `1.16`, `1.17`, `1.18` so trying to cherry-pick your commit `7670d7b6af6cf98e29f7f328d8de38072f7a0d9a` into the respective branches like `cluster-autoscaler-release-1.15`, `cluster-autoscaler-release-1.16` and so on, but there are conflicts in several files like `cluster-autoscaler/utils/deletetaint/delete.go` `cluster-autoscaler/main.go` `cluster-autoscaler/config/autoscaling_options.go`

would you be able to provide the fixes in other branches as well instead of master?

2021-04-05 16:33 UTC, Jeffwan commented
> @Jeffwan i've created a dev docker release for my staging testing, still waiting on the official release for prod.
> Do you know when it is going to happen? i'm waiting for a release on k8s 1.18.
> Thanks

@ltagliamonte-dd Please cherry-pick this change to release branch. @kubernetes/autoscaler-maintainers will help cut release later.