Bump github.com/heketi/heketi to v10.1.0
kubernetes/autoscaler pull request #3708
Opened 2020-11-19 16:27 UTC by JoelSpeed

Heketi recently released a version that includes some security fixes, this PR bumps this dependency to the new version to ensure that the security leak is fixed

From their release notes:
> An information-disclosure flaw was found in the way Heketi logs sensitive
information. This flaw allows an attacker with access to the Heketi server logs
to read potentially sensitive information, such as the CHAP passwords for
gluster-block volumes (CVE-2020-10763).

I deliberately kept K/K pinned at the previous version to minimise the diff when reviewing. This hasn't been fixed in K/K yet so had to add an override to go.mod-extra.

2020-11-19 17:24 UTC, elmiko approved these changes
i'm not sure about the cluster-autoscaler policy on using go.mod-extra, but this looks good to me
/lgtm

2020-11-19 23:27 UTC, mwielgus requested changes
We try to stay consistent with kubernetes/kubernetes regarding dependencies and their versions. Otherwise we may run into unfixable/very time consuming issues on our next sync. So this version update has to wait for k/k.

2020-11-20 12:49 UTC, JoelSpeed commented
Ok, no worries, I've added a K/K PR, will see if that can be merged https://github.com/kubernetes/kubernetes/pull/96749 and then I'll revisit this

2020-12-03 14:21 UTC, mwielgus commented
Then this should happen automatically with the next dependencies sync. Closing this PR for now.

2020-12-03 14:21 UTC, closed without merging