Change behaviour of Garbage Collector
kubernetes/autoscaler pull request #4425
Opened 2021-10-27 13:06 UTC by piotrnosek

Only remove AggregateCollectionStates which don't have an existing corresponding controller (e.g. Deployment).

2021-11-02 17:09 UTC, piotrnosek commented on vertical-pod-autoscaler/pkg/recommender/model/cluster.go
> +func (cluster *ClusterState) garbageCollectAggregateCollectionStates(now time.Time, controllerFetcher controllerfetcher.ControllerFetcher) {
Actually all points are still true, just the definition of active pod changed. Before an inactive pod would be a pod that is in a terminal state (succeeded/failed). Right now, an inactive pod is a pod which is both in a terminal state and doesn't have an existing controller. I've added a comment to reflect that.

This doesn't change the logic for old samples (>8 days old) and old aggregates.

2021-11-15 18:11 UTC, jbartosik requested changes

2021-11-15 18:11 UTC, jbartosik commented on vertical-pod-autoscaler/pkg/recommender/model/cluster.go
> +func (cluster *ClusterState) garbageCollectAggregateCollectionStates(now time.Time, controllerFetcher controllerfetcher.ControllerFetcher) {
Saying pod is active when its phase is not one of {PodSucceeded, PodFailed} makes sense to me.

Saying pod is active when its phase is not one of {PodSucceeded, PodFailed} or there is a controller for it looks unintuitive to me.

Please:
- update this change to keep previous definition of active and add having a controller as a separate condition, or
- pick a new word for the concept "has a controller or isn't in a terminal phase".

2021-12-02 08:28 UTC, jbartosik commented
@piotrnosek please rebase this PR on top of current master, it looks like it has a lot of changes that shouldn't be here.

2021-12-02 13:42 UTC, piotrnosek commented
Closing this PR due to running into rebase hell with git, desired changes are on a separate PR: https://github.com/kubernetes/autoscaler/pull/4488.

2021-12-02 13:42 UTC, closed without merging