[CA] [AWS examples] Add container securityContext
kubernetes/autoscaler pull request #4478
Opened 2021-11-24 15:36 UTC by damienleger

Hello,

Since some security parameters aren't configurable in [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#podsecuritycontext-v1-core) I introduced a new [container Security Context](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#securitycontext-v1-core) to add security best practices.

- container is now immutable (file integrity guaranteed): readOnlyRootFilesystem
- remove rights the application doesn't need: allowPrivilegeEscalation+capabilities

This follow the least privilege principle in security. Configuration recommanded by scanners such as [kubescape](https://github.com/armosec/kubescape).

Tested in my EKS 1.21 cluster with `cluster-autoscaler-autodiscover.yaml` using container image v1.22. I don't see anything wrong in the logs.

2021-11-25 09:50 UTC, gjtempleton commented
/area provider/aws

2022-02-24 06:04 UTC, damienleger commented
/remove-lifecycle stale

2022-05-25 07:39 UTC, damienleger commented
/remove-lifecycle stale

2022-07-01 06:59 UTC, joebowbeer commented
For PSS/restricted, a seccompProfile type RuntimeDefault is also required.

https://kubernetes.io/docs/concepts/security/pod-security-standards/

I suggest you run kyverno apply against the manifest to check for any gaps.

2022-07-01 07:00 UTC, joebowbeer requested changes
ALL should be capitalized.

Missing RuntimeDefault seccompProfile.

2022-11-14 19:37 UTC, joebowbeer commented
@damienleger I applied the PSS/restricted policies to your branch and there are (only!) two failures:

```shell
kyverno apply <(kustomize build http://github.com/kyverno/policies//pod-security) -r \
  <(wget -qO- https://raw.githubusercontent.com/damienleger/autoscaler/container_security_context/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml)
```

```
policy disallow-host-path -> resource kube-system/Deployment/cluster-autoscaler failed:
1. autogen-host-path: validation error: HostPath volumes are forbidden. The field spec.volumes[*].hostPath must be unset. rule autogen-host-path failed at path /spec/template/spec/volumes/0/hostPath/

policy restrict-volume-types -> resource kube-system/Deployment/cluster-autoscaler failed:
1. autogen-restricted-volumes: Only the following types of volumes may be used: configMap, csi, downwardAPI, emptyDir, ephemeral, persistentVolumeClaim, projected, and secret.
```

It's still complaining about the ssl-certs volume and mount; I don't know if there is a way around this:

```yaml
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt #/etc/ssl/certs/ca-bundle.crt for Amazon Linux Worker Nodes
              readOnly: true
```

```yaml
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"
```

2022-11-15 10:21 UTC, damienleger commented
@joebowbeer I see, nice. About this hostPath volume, only way around this I think of right now is
a) mount an EmptyDir volume in /etc/ssl/certs/ and download the CA bundles inside via initContainer or some script at pod startup
b) embed the CA bundle inside docker image

a) is okay I think but more complicated, b) feels not viable in time (image can embed deprecated CA)

I think it's okay to let hostPath like this. After all cluster-autoscaler is a kube-system workload. I am a kyverno user myself btw, and I have exceptions on kube-system workloads and workloads taking care of monitoring and logshipping; it's not shocking to me.

2022-11-15 11:03 UTC, joebowbeer commented
@damienleger I agree. LGTM

2022-11-15 11:04 UTC, joebowbeer approved these changes

2022-12-15 14:32 UTC, joebowbeer commented
/remove-lifecycle rotten

2022-12-15 16:07 UTC, damienleger commented
hello @joebowbeer , is something expected for me to get this PR merged? I'm confused by the process

2022-12-15 20:31 UTC, joebowbeer commented
> hello @joebowbeer , is something expected for me to get this PR merged? I'm confused by the process

Hi, I don't know any more than the bot [comment](https://github.com/kubernetes/autoscaler/pull/4478#issuecomment-1315149109) says.

It looks like @gjtempleton is assigned to review; once reviewed @jaypipes will/should be assigned to approve.

I would try posting in [#sig-autoscaling](https://kubernetes.slack.com/archives/C09R1LV8S) on Kubernetes slack. All the listed owners are there.

2023-02-28 16:23 UTC, x13n commented
Can you take a look?

/assign @jaypipes @gjtempleton

2023-03-06 22:25 UTC, gjtempleton commented
Thanks!

/lgtm
/approve

2023-03-06 22:26 UTC, merged