Implement external gRPC Cloud Provider
kubernetes/autoscaler pull request #4654
Opened 2022-01-30 12:31 UTC by dbonfigli

#### Which component this PR applies to?

cluster-autoscaler

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Add a cloud provider to allow external implementations as described in the proposal #3140 [Pluggable Cloud Provider over gRPC](https://github.com/kubernetes/autoscaler/blob/68c984472acce69cba89d96d724d25b3c78fc4a0/cluster-autoscaler/proposals/plugable-provider-grpc.md)

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
New cloud provider: external gRPC
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-02-21 14:48 UTC, mwielgus requested changes

2022-02-21 14:49 UTC, mwielgus commented
Please add OWNERS file (possibly with commented-out names) so we know who to contact in case of bugs, issues, reviews etc.

2022-02-21 16:44 UTC, dbonfigli commented on cluster-autoscaler/cloudprovider/externalgrpc/examples/external-grpc-cloud-provider-service/main.go
> +Copyright 2019 The Kubernetes Authors.
Updated.

2022-02-21 16:44 UTC, dbonfigli commented
> Please add OWNERS file (possibly with commented-out names) so we know who to contact in case of bugs, issues, reviews etc.

Added.

2022-05-04 13:09 UTC, mwielgus approved these changes
/lgtm
/approve

2022-05-04 13:11 UTC, merged