add flag to ignore requests scaling up or down
kubernetes/autoscaler pull request #5012
Opened 2022-07-07 06:01 UTC by ganga1980

#### Which component this PR applies to?

addon-resizer
#### What type of PR is this?
feature 

#### What this PR does / why we need it:
This PR exposes flag to ignore the scaling of the requests and only scale the limits. In large clusters, scaling requests will cause the scheduling issues for other workload pods.  This flag enables to scale only the limits and have the specified fixed requests as is.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
Yes

```release-note
Introduced --ignoreResourceRequests flag to ignore the scaling of the resource requests.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-07-11 23:05 UTC, ganga1980 commented
Hi, @jbartosik, @wojtek-t, can you guys help on reviewing this PR?

2022-07-18 05:42 UTC, ganga1980 commented
Hi, @jbartosik , @wojtek-t , Appreciate your help on reviewing this PR as I would like to get this change merged soon.

2022-07-18 08:08 UTC, voelzmo commented
I can't really comment on the functionality itself so here's just a comment regarding the "how it is done": given that we have already a setting for which values are to be controlled by the VPA ([`controlledValues`](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L184) with currently possible values `RequestsOnly` and `RequestsAndLimits`), it would probably better fit in there as `LimitsOnly`.

2022-07-19 05:12 UTC, ganga1980 commented
Hi,  @jbartosik , can you please help on reviewing this PR?

2022-07-20 04:55 UTC, ganga1980 commented
Hi, @jbartosik, @wojtek-t , sorry to bug you guys on this. If you guys don't have cycles to review, can you please tag the folks who can help on reviewing this PR?

2022-07-20 13:09 UTC, jbartosik commented
Hi, I don't have capacity to review this. I'm pretty sure Wojciech doesn't either.

I'll ask if someone wants to review this on the next [SIG meeting](https://github.com/kubernetes/community/blob/master/sig-autoscaling/README.md#meetings) on Monday. You can try also try asking for volunteers on Slack.

2022-07-22 14:55 UTC, ganga1980 commented
/assign @mainred

2022-07-27 15:19 UTC, shreyas-badiger commented
@ganga1980 
The description in the first comment is not entirely clear. Can you please update the PR with the following? 
- Clear documentation of the flag and its requirement.
- Testing proof, unit tests
- PR details for the release notes

2022-08-10 10:43 UTC, mwielgus requested changes

2022-08-10 10:43 UTC, mwielgus commented on addon-resizer/README.md
> +      --ignoreResourceRequests=false: ignoring scaling up or down of the resource requests if this flag is true.
It is hard to tell what this flag actually does when specified. Expand the description and/or change the flag name (for example scaleResourceRequest with the default set to true would be much more intuitive).

2022-08-10 10:43 UTC, mwielgus commented on addon-resizer/nanny/kubernetes_client_test.go
> +			got := mergeResources(tc.current, tc.new, false)
This is a new functionality and thus requires some tests. Please add them.

2022-08-10 10:43 UTC, mwielgus commented on addon-resizer/nanny/nanny_lib_test.go
> +		gotOverwrite, gotOp := shouldOverwriteResources(tc.th, tc.x, tc.x, tc.y, tc.x, false)
Add tests with true.

2023-03-05 19:36 UTC, closed without merging