Don't say that `Recreate` and `Auto` VPA modes are experimental
kubernetes/autoscaler pull request #5289
Opened 2022-11-03 09:21 UTC by jbartosik

#### Which component this PR applies to?

VPA

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #5245

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-11-03 13:19 UTC, voelzmo requested changes
There's two small typos and I think we also need to change the wording in the **Known Limitations** section as well. It still has 
> Updating running pods is an experimental feature of VPA.

2022-11-03 13:19 UTC, voelzmo commented on vertical-pod-autoscaler/README.md
> +  should mitigagte the problem.
```suggestion
  should mitigate the problem.
```

small typo

2022-11-03 13:19 UTC, voelzmo commented on vertical-pod-autoscaler/README.md
> +  should mitigagte the problem.
```suggestion
  should mitigate the problem.
```

small typo

2022-11-04 09:44 UTC, jbartosik commented
I can't push fixes to this PR, I'm doing #5293 instead.

2022-11-04 09:44 UTC, closed without merging