Fix for 'Link for cloud-controller-manager is not working'
kubernetes/autoscaler pull request #5346
Opened 2022-12-02 19:37 UTC by McGon-Fid

Making a minor document link change in kubernetes autoscaler FAQ.md.

Issue is here: #5332

2022-12-03 15:15 UTC, gjtempleton requested changes
One slight fix required

2022-12-03 15:15 UTC, gjtempleton commented on cluster-autoscaler/FAQ.md
> +It does _not_ delete the [Node object](https://kubernetes.io/docs/concepts/architecture/nodes/#api-object) from Kubernetes. Cleaning up Node objects corresponding to terminated instances is the respo
Duplication of `https://`:
```suggestion
It does _not_ delete the [Node object](https://kubernetes.io/docs/concepts/architecture/nodes/#api-object) from Kubernetes. Cleaning up Node objects corresponding to terminated instances is the responsibility of the [cloud node controller](https://kubernetes.io/docs/concepts/architecture/cloud-controller/#node-controller), which can run as part of [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) or [cloud-controller-manager](https://kubernetes.io/docs/concepts/architecture/cloud-controller/).
```

2022-12-05 09:56 UTC, McGon-Fid commented
@gjtempleton thank you. I've now committed the suggested change for review. 

Correcting URL syntax for document link change in kubernetes autoscaler FAQ.md.

Issue is here: https://github.com/kubernetes/autoscaler/issues/5332

2022-12-05 13:33 UTC, mwielgus approved these changes
/lgtm
/approve

2022-12-05 13:35 UTC, merged