Update image references from k8s.gcr.io to registry.k8s.io
kubernetes/autoscaler pull request #5494
Opened 2023-02-10 09:18 UTC by salasberryfin

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

On the 3rd of April 2023, the old registry `k8s.gcr.io` will be frozen and no further images for Kubernetes and related subprojects will be pushed to the old registry. This PR updates the image references to point to the new registry `registry.k8s.io`

#### Which issue(s) this PR fixes:

Fixes #5491

#### Special notes for your reviewer:

There are a couple of references in `vertical-pod-autoscaler/RELEASE.md`:
- [Images](https://github.com/kubernetes/autoscaler/blob/98e319b99ddaf50ceb7c6db3fbe0cb513d66843d/vertical-pod-autoscaler/RELEASE.md?plain=1#L81)
- [OWNERS](https://github.com/kubernetes/autoscaler/blob/98e319b99ddaf50ceb7c6db3fbe0cb513d66843d/vertical-pod-autoscaler/RELEASE.md?plain=1#L145)

that link to [kubernetes/k8s.io](https://github.com/kubernetes/k8s.io) and the folder [k8s.gcr.io](https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io). The files referenced by these links cannot be found under the path of the new registry [registry.k8s.io](https://github.com/kubernetes/k8s.io/tree/main/registry.k8s.io). Do we ignore these references as with `staging-k8s.gcr.io`?

#### Does this PR introduce a user-facing change?

NONE

2023-02-10 09:26 UTC, voelzmo commented
Hey @salasberryfin thanks for picking this up!
I think you have a few changes in the respective `/vendor` directories, which probably occurred due to search-and-replace? I think in this change, only the image references in the `.yaml` files need to be adapted and we don't expect anything to change in `/vendor`, so please revert these. Thanks!

2023-02-10 09:37 UTC, salasberryfin commented
> Hey @salasberryfin thanks for picking this up! I think you have a few changes in the respective `/vendor` directories, which probably occurred due to search-and-replace? I think in this change, only the image references in the `.yaml` files need to be adapted and we don't expect anything to change in `/vendor`, so please revert these. Thanks!

Hi @voelzmo, sorry about that, I'll revert those changes. There are other references to the old registry that I've modified in go files under `e2e/v1`, do I revert those as well to change only yaml files?

Thanks!

2023-02-12 20:44 UTC, salasberryfin commented
Hello @apricote @deitch,

Not sure why one of the test cases is failing. Can i have some help with this?

Thanks.

2023-02-13 07:38 UTC, apricote commented
You made changes to the Helm Chart `charts/cluster-autoscaler` and the `ct lint` steps checks that the version number in the Helm Chart is also updated with any changes. To fix this, you need to increment the version in `charts/cluster-autoscaler/Chart.yaml`. Example PR that raised the version last time: [#5390](https://github.com/kubernetes/autoscaler/pull/5390/files#diff-853ed46c65f63241cf21281a8fea207eef33a5313bf911a0dae8429f6c05f941R14)

2023-02-13 08:49 UTC, salasberryfin commented
@apricote, thanks for the help! I think it is solved now.

2023-02-13 08:50 UTC, apricote commented
/lgtm

2023-02-13 13:11 UTC, gjtempleton requested changes
Thanks for picking this up!

One comment unrelated to your changes, and one request on the chart version.

You're correct on leaving the references `that link to kubernetes/k8s.io and the folder k8s.gcr.io.` as they are.

2023-02-13 15:32 UTC, salasberryfin commented on charts/cluster-autoscaler/Chart.yaml
> +version: 9.24.1
Thanks for the review.

I had to rebase to get the latest changes from the main branch and just updated it to match the `version`. Fixing it now.

2023-02-13 15:34 UTC, salasberryfin commented on cluster-autoscaler/cloudprovider/vultr/examples/cluster-autoscaler-deployment.yaml
> +        - image: registry.k8s.io/autoscaling/cluster-autoscaler:latest
Do we keep this open for them to review or can we resolve and let them manage it on their own issue?

2023-02-13 16:14 UTC, gjtempleton commented on cluster-autoscaler/cloudprovider/vultr/examples/cluster-autoscaler-deployment.yaml
> +        - image: registry.k8s.io/autoscaling/cluster-autoscaler:latest
Happy to merge as is and raise a separate issue for them to resolve it.

2023-02-14 08:16 UTC, salasberryfin commented
I had to rebase again but I think it is now ready to be reviewed and merged.

2023-02-14 09:25 UTC, gjtempleton commented
Thanks again!
/lgtm
/approve

2023-02-14 09:27 UTC, merged