Balancer controller implementation
kubernetes/autoscaler pull request #5495
Opened 2023-02-10 10:59 UTC by mwielgus

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Implementation of the Balancer controller.

2023-02-24 13:17 UTC, pbetkier approved these changes
/lgtm

2023-02-24 15:14 UTC, voelzmo requested changes
Hey @mwielgus I had a look and have a few general questions regarding the structure. Sorry I didn't get to looking at the details of the implementation yet.

* It seems we merged the `balancer` API under [module path `k8s.io/autoscaling`](https://github.com/kubernetes/autoscaler/blob/master/balancer/go.mod#L1), whereas all other components in this repo define modules under `k8s.io/autoscaler`, so I guess we should either correct this first or make it part of this PR?
* I assume `k8s.io/gke-autoscaling` is an internal package location and should rather be `k8s.io/autoscaler` in all occurrences? This is also present in generated files, so I guess these would need to be re-generated afterwards
* Should we add `k8s.io/code-generator` to the dependencies and check in some `hack/update-codegen.sh` script to make it easy to re-generate everything?
* Did you intentionally decide against checking in `vendor`, maybe because of https://github.com/kubernetes/autoscaler/issues/4878? I'm just asking this, because currently all other components in this repo have their `vendor` checked in.

2023-03-16 12:50 UTC, mwielgus commented on balancer/pkg/controller/conditions.go
> +	"k8s.io/gke-autoscaling/balancer/pkg/apis/balancer.x-k8s.io/v1alpha1"
Fixed.

2023-03-20 14:28 UTC, pbetkier commented
/lgtm

2023-03-24 13:52 UTC, mwielgus commented on balancer/pkg/controller/core_test.go
> +				newScale("b", 0),
Scale represents the current reported state of the world. The numbers may be however a bit outdated, the code doesn't care about that number too much.

2023-03-24 15:41 UTC, voelzmo commented on balancer/pkg/controller/core_test.go
Thanks for the explanation! This was a bit non-obvious to me in the Priority policy: that _one_ failing Pod indicates that the fallback solution is applied to _all outstanding_ replicas while still trying to place all replicas in A. So this means in the worst case, we would end up temporarily with `2*n-1` running replicas with `n` being the amount of replicas configured in the Balancer, correct?

2023-03-24 15:49 UTC, mwielgus commented on balancer/pkg/controller/core_test.go
Yes, for a brief moment. As soon as there is N running pods on the first deployment, the second one will be scaled down to 0.

2023-03-27 08:35 UTC, voelzmo commented
/lgtm

2023-03-27 08:35 UTC, merged

2023-03-27 16:39 UTC, grosser commented
some docs would be great, on what this does and how to use it

2023-03-27 16:41 UTC, gjtempleton commented
@grosser you can see the initial proposal presenting the problem it aims to address here: https://github.com/kubernetes/autoscaler/blob/master/balancer/proposals/balancer.md