Draft: fix: [ISS-5465] add a flag to let CA delegate node deletion to the cloud provider
kubernetes/autoscaler pull request #5538
Opened 2023-02-27 21:22 UTC by wmgroot

#### What type of PR is this?
/kind bug
/kind api-change

#### What this PR does / why we need it:
Cluster Autoscaler currently tries to remediate nodes that fail to join a cluster by deleting them. This is helpful to retry nodes sooner, but CA does not have a good way to delete nodes available to it. To accomplish this, it uses the replica count on a node group resource to downsize the number of desired nodes after marking a node with an annotation that the cloud provider should prefer this node for deletion.

During this period of time, the desired count of replicas is incorrect. Furthermore, this behavior can occur multiple times in parallel, resulting in multiple node deletions occurring simultaneously, which can significantly decrease the number of desired replicas in a node group far below what is actually needed to run all the pods that would schedule in that node group.

If a significant number of nodes fail to join the cluster, this can result in node groups operating with desired replica counts far below their actual intended replica count for extended periods of time, resulting in losses of cluster capacity and evicted pods with no node to schedule on.

#### Which issue(s) this PR fixes:

Fixes #5465

#### Special notes for your reviewer:
This change unfortunately is not compatible across all existing cloud providers, since it requires cloud provider specific implementation of marking nodes for deletion instead of downscaling the replica counts in certain situations. Previously, DeleteNodes() handled all cases equally.

#### Does this PR introduce a user-facing change?

```release-note
No immediate user-facing changes are required. This change is gated behind a feature gate applied as an arg to CA. By default the behavior is unchanged.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-02-28 10:57 UTC, x13n commented
/assign

2023-02-28 11:04 UTC, x13n requested changes
I'm not convinced this requires cloud provider interface change. Why can't it be an option on Cluster API cloud provider level to control whether nodes are removed by CA or just marked by CA for removal by cloud provider?

2023-03-02 21:55 UTC, wmgroot commented on cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
> +	markMachineForDeleteAnnotationKey = getMarkMachineForDeleteAnnotationKey()
I'm adding this at the recommendation of the cluster-api maintainers to avoid breaking the existing behavior of the `delete-machine` annotation.

2023-03-03 09:22 UTC, x13n commented
> I don't think the CAPI cloud provider implementation of DeleteNodes() would have a way to tell if DeleteNodes was called as a scale down event vs clean up of nodes that are failing to join the cluster.

Why not? It would be exactly the same - through a commandline flag. The only difference would be that all the other cloud providers wouldn't have to have the boilerplate "not implemented" methods and that the flag would live somewhere under `cloudprovider/clusterapi` dir, rather than in `main.go`.

2023-03-03 14:41 UTC, wmgroot commented
> > I don't think the CAPI cloud provider implementation of DeleteNodes() would have a way to tell if DeleteNodes was called as a scale down event vs clean up of nodes that are failing to join the cluster.
> 
> Why not? It would be exactly the same - through a commandline flag. The only difference would be that all the other cloud providers wouldn't have to have the boilerplate "not implemented" methods and that the flag would live somewhere under `cloudprovider/clusterapi` dir, rather than in `main.go`.

I'm not completely following. There are 3 places where DeleteNodes() is called outside of any cloudprovider implementation. The solution requires that we handle 2 of those 3 calls (failed node cases) differently, and leave the existing behavior alone in the last (scaledown case). The cluster-api implementation has no idea which of the 3 potential DeleteNode() paths is being triggered unless we make a change to break it into 2 separate functions, or pass an additional parameter in DeleteNodes() to allow branching functionality in the provider implementations of the function.

Furthermore, I believe this issue is not limited to the cluster-api implementation. Other cloud provider implementations of DeleteNodes() reduce the replica count of their node groups as a way to delete failing nodes. This is flawed behavior, and should be corrected. The replica count should always reflect the desired state of the cluster, even when nodes are failing to join the cluster quickly.

2023-03-03 19:15 UTC, elmiko commented
this pr generally makes sense to me, and i get what you are saying @wmgroot about the provider not knowing the difference between the 2 types of deletion. i think it would be good to bring this issue to a SIG if possible to get a few more ideas about if we should expand the interface.

i'd also like to study this a little more to better understand the different deletion methodologies and how those interact with the cluster-api provider. thanks @wmgroot for such a thorough pr.

2023-03-03 22:04 UTC, wmgroot commented
Sounds good to me. We've got the Monday SIG Autoscaling meeting on our calendars, and I should be able to bring this up there for further discussion.

We're going to do some more testing around how this shift in behavior plays with fallback scenarios, since CA would still want to reduce replica counts for a node group that failed to have a node join if it will be switching to a new fallback node group.

2023-03-06 15:28 UTC, elmiko commented
apologies @wmgroot , i had a conflict today and was not able to make the meeting. i'm happy to help with followups if i can.

2023-03-06 15:53 UTC, x13n commented
Apologies on my end as well - I didn't make it to the SIG meeting either. I see from the meeting notes you're following up on this with @MaciekPytel. Is this PR on hold for now?

2023-03-06 17:49 UTC, wmgroot commented
@MaciekPytel mentioned that there was some nuance to be understood about DecreaseTargetSize() vs DeleteNodes(). It might be possible for the replica reduction logic present in the cluster-api implementation of DeleteNodes() to be handled by DecreaseTargetSize() instead.

I think we should put review of this PR on hold until that possibility can be explored. I can update here once that's happened.

2023-03-07 19:51 UTC, elmiko commented
thanks for the update @wmgroot , i'm fine to put this on hold until you are ready to move forward. feel free to remove the hold when you are ready.

/hold for further investigation

2023-03-24 18:31 UTC, wmgroot commented
Alright, sorry for the delay, things got busy at the end of quarter for me.
I've tested trying to avoid the use of any new flags by tweaking the CAPI logic to only decrease replicas of a node group when DecreaseTargetSize() is called.

This did not work. In my test case I have 2 nodes that have nothing scheduled to them (other than daemonsets).
```
$ kubectl get machine -n capi-awscmhdev2 --context awscmhdev2
NAME                                                   CLUSTER      NODENAME                                       PROVIDERID                              PHASE          AGE     VERSION
worker-private-test-ca-az2-744477878-bxpqk             awscmhdev2   ip-10-115-223-57.us-east-2.compute.internal    aws:///us-east-2b/i-0fe56f28fa8b8be30   Running        10d     v1.24.7
worker-private-test-ca-az2-744477878-gvpp5             awscmhdev2   ip-10-115-213-94.us-east-2.compute.internal    aws:///us-east-2b/i-0b31e1f26e69e23e9   Running        10d     v1.24.7
```

CA still identifies that the nodes should be deleted, but does not ever actually delete the unneeded nodes.
```
I0324 18:07:56.806731       1 klogx.go:87] Node ip-10-115-223-57.us-east-2.compute.internal - cpu utilization 0.233571
I0324 18:07:56.807114       1 nodes.go:84] ip-10-115-223-57.us-east-2.compute.internal is unneeded since 2023-03-24 18:05:31.597356663 +0000 UTC m=+3033.013308437 duration 0s
I0324 18:08:06.605511       1 nodes.go:126] ip-10-115-223-57.us-east-2.compute.internal was unneeded for 0s
I0324 18:08:06.626397       1 taints.go:135] Successfully added DeletionCandidateTaint on node ip-10-115-223-57.us-east-2.compute.internal
I0324 18:10:57.034238       1 klogx.go:87] Node ip-10-115-223-57.us-east-2.compute.internal - cpu utilization 0.233571
I0324 18:10:57.038712       1 nodes.go:84] ip-10-115-223-57.us-east-2.compute.internal is unneeded since 2023-03-24 18:05:31.597356663 +0000 UTC m=+3033.013308437 duration 2m54.827681204s
I0324 18:11:11.232802       1 nodes.go:126] ip-10-115-223-57.us-east-2.compute.internal was unneeded for 2m54.827681204s
I0324 18:11:11.244785       1 taints.go:135] Successfully added ToBeDeletedTaint on node ip-10-115-223-57.us-east-2.compute.internal
I0324 18:11:11.244973       1 event_sink_logging_wrapper.go:48] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-115-223-57.us-east-2.compute.internal", UID:"e41a2ddf-12ce-4a44-8de6-15292ed65286", APIVersion:"v1", ResourceVersion:"488849061", FieldPath:""}): type: 'Normal' reason: 'ScaleDown' marked the node as toBeDeleted/unschedulable
I0324 18:11:12.015497       1 actuator.go:160] Scale-down: removing empty node "ip-10-115-223-57.us-east-2.compute.internal"
I0324 18:11:12.021442       1 event_sink_logging_wrapper.go:48] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"capi-awscmhdev2", Name:"cluster-autoscaler-status", UID:"0f83dc30-13e4-4769-aef5-df069f60cb20", APIVersion:"v1", ResourceVersion:"488849019", FieldPath:""}): type: 'Normal' reason: 'ScaleDownEmpty' Scale-down: removing empty node "ip-10-115-223-57.us-east-2.compute.internal"
I0324 18:14:16.263272       1 eligibility.go:111] Skipping ip-10-115-223-57.us-east-2.compute.internal from delete consideration - the node is currently being deleted
```

This is because DecreaseTargetSize() is only ever called during one code path, in fixNodeGroupSize(), which is not part of the standard scaledown path. Scale down currently relies on DeleteNodes() to perform the actual scale down of a node group. This seems inherently wrong to me if I consider what the intent of each function should be based on its name.

So I think we're back to square one with this; I do not see any way to start untangling these assumptions that can result in incorrect replica count reduction in certain cases without adding a flag. These are the options that I think we have.
* Update DeleteNodes to only delete nodes across all cloud providers and start calling DecreaseTargetSize() as part of the standard scaledown path (too much work for one PR).
* Do the above, but enable a flag to allow users to contribute fixes to each cloud provider one at a time.
* Implement the current PR, which works around the issue by separating the cases where replicas should and should not be scaled down by adding a function that deletes nodes without downscaling the node groups (this PR).

I'll plan to pop into the next CA contributor meeting to discuss further.

2023-04-03 11:35 UTC, x13n commented
/assign @MaciekPytel 

Thoughts on this one?

2023-05-31 10:22 UTC, elmiko commented
i think the flag addition is probably the simplest way to solve this, at the expense of adding a new interface function. i'd like to talk about this again at an upcoming SIG meeting since this seems like it is going to affect cluster-api users the most.

2023-05-31 10:28 UTC, elmiko reviewed
aside from the printf comment, my only other question is should we emit warnings for the providers that do not implement this as it will help debugging for users who might enable this flag without fully understanding the implications?

2023-05-31 10:28 UTC, elmiko commented on cluster-autoscaler/core/static_autoscaler.go
> +				fmt.Printf("MarkNodesForDeletion (removeOldUnregisteredNodes)\n")
i think we'll need to upgrade these printf's to log messages, perhaps using `V(2).InfoS` level.

2023-10-13 08:00 UTC, x13n commented
Closing due to lack of activity. Please reopen if still relevant.

/close

2023-10-13 08:00 UTC, closed without merging