Simplify the GCE client FetchMigInstances function.
kubernetes/autoscaler pull request #5557
Opened 2023-03-02 12:58 UTC by kisieland

Also export the GetErrorInfo function which maps
GCE response to correct error class.

Change-Id: I206f55fef0e14f05a2bfc8e7b712ab6f1d4183b8

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Simplifies the FetchMigInstances function and moves the error handling to a dedicated function. \
This makes writing of the custom GCE client easier.

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-03-03 09:58 UTC, kisieland commented
/reviewer x13n

2023-03-03 10:17 UTC, kisieland commented
/assign @x13n

2023-03-03 16:16 UTC, x13n requested changes

2023-03-13 11:01 UTC, kisieland commented on cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
> +func isInstanceNotRunningYet(instanceStatus string) bool {
done

2023-03-13 12:27 UTC, kisieland commented on cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
> +			klog.Errorf("Received error while parsing of the instance url: %v", err)
Added tests, as in comment, for now those are independent commits and I can split those into independent PRs if you prefer.

2023-03-14 10:03 UTC, x13n commented
/lgtm
/approve

2023-03-14 10:04 UTC, merged