[helm chart] Update to use cluster-autoscaler 1.26.2 + default tag value from the Chart's AppVersion
kubernetes/autoscaler pull request #5640
Opened 2023-03-30 16:04 UTC by asherf

This is similar to how it is done in other chats:
https://github.com/kubernetes/dashboard/blob/313af7c8e1922fb4d7c6be4dc3fc006e286e759a/charts/helm-chart/kubernetes-dashboard/templates/deployment.yaml#L66 https://github.com/kubernetes/dashboard/blob/313af7c8e1922fb4d7c6be4dc3fc006e286e759a/charts/helm-chart/kubernetes-dashboard/values.yaml#L23

/kind feature

2023-03-30 16:53 UTC, asherf commented
not sure about the docs lint fail.... any pointers ?

2023-04-03 06:02 UTC, gjtempleton requested changes
Hey, thanks for the PR.

We use and enforce helm-docs to generate our chart README, which is why the CI is currently failing, you can either set it up as a [pre-commit hook](https://github.com/kubernetes/autoscaler/tree/master/charts#pre-commit-hooks) or run it manually.

2023-04-03 06:02 UTC, gjtempleton commented on charts/cluster-autoscaler/values.yaml
> +  tag: ""  # If not defined, uses appVersion of Chart.yaml
```suggestion
  # image.tag - Image tag - defaults to the version defined in Chart.AppVersion
  tag: ""  # If not defined, uses appVersion of Chart.yaml
```

2023-04-03 06:16 UTC, gjtempleton commented
On balance I'm not sure this is a path we want to take with the CA given versions of the CA are so closely tied to the version of kubernetes and mismatching minor versions between these can result in unexpected behaviour.

There's been a previous request to look at automatically picking an image to match the minor version of the underlying cluster as per #5324.

2023-04-03 14:49 UTC, asherf commented
> On balance I'm not sure this is a path we want to take with the CA given versions of the CA are so closely tied to the version of kubernetes and mismatching minor versions between these can result in unexpected behaviour.
> 
> There's been a previous request to look at automatically picking an image to match the minor version of the underlying cluster as per #5324.

good point.
closing in favor of https://github.com/kubernetes/autoscaler/pull/5640#issuecomment-1493723676
I appreciate the feedback and the guidance on using pre-commit, I somehow missed that.

2023-04-03 14:49 UTC, closed without merging