Add requirement for Custom Resources to VPA FAQ
kubernetes/autoscaler pull request #5979
Opened 2023-07-24 15:20 UTC by voelzmo

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
As discussed in today's SIG meeting: Let's add the contract for VPA's support for Custom Resources more explicitly to the FAQ, as this question [keeps](https://github.com/kubernetes/autoscaler/issues/5836) [coming](https://github.com/kubernetes/autoscaler/issues/5925) [back](https://github.com/kubernetes/autoscaler/issues/3766).

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2023-07-24 15:20 UTC, voelzmo commented
/invite @jbartosik

2023-07-25 11:49 UTC, Shubham82 requested changes

2023-07-25 11:49 UTC, Shubham82 commented on vertical-pod-autoscaler/FAQ.md
> +Custom Resource. As VPA relies on Pod eviction to apply new resource recommendations, this ensures that all Pods with a matching VPA object are managed by a controller that will recreate them after e
nit: Wrap the line
```suggestion
Custom Resource. As VPA relies on Pod eviction to apply new resource recommendations, this
ensures that all Pods with a matching VPA object are managed by a controller that will
recreate them after eviction. Furthermore, it avoids misconfigurations that happened in the
past when label selectors were specified manually.
```

2023-07-25 11:50 UTC, Shubham82 commented
@voelzmo content looks good to me, just small nits.

2023-07-26 12:48 UTC, voelzmo commented on vertical-pod-autoscaler/FAQ.md
> +which corresponds to `.scale.status.selector`. VPA doesn't use the `/scale` subresource for the actual scaling, but uses this label selector to identify the Pods managed by a
done.

2023-07-26 12:48 UTC, voelzmo commented on vertical-pod-autoscaler/FAQ.md
> +Custom Resource. As VPA relies on Pod eviction to apply new resource recommendations, this ensures that all Pods with a matching VPA object are managed by a controller that will recreate them after e
done.

2023-07-27 04:15 UTC, Shubham82 commented
Thanks @voelzmo 
/lgtm

2023-07-27 14:18 UTC, jbartosik reviewed
Mostly looks good,  I made a couple small suggestions

2023-07-27 14:18 UTC, jbartosik commented on vertical-pod-autoscaler/FAQ.md
> +The VPA cannot only scale the built-in resources like Deployment or StatefulSet, but also Custom Resources which manage
```suggestion
The VPA can scale not only the built-in resources like Deployment or StatefulSet, but also Custom Resources which manage
```

2023-07-27 14:18 UTC, jbartosik commented on vertical-pod-autoscaler/FAQ.md
> +subresource with the optional field `labelSelector`](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource),
```suggestion
Pods. Just like the Horizontal Pod Autoscaler, the VPA requires that the Custom Resource implements the
[`/scale` subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource)
with the optional field `labelSelector`,
```

2023-07-28 07:36 UTC, voelzmo commented on vertical-pod-autoscaler/FAQ.md
> +subresource with the optional field `labelSelector`](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource),
Thanks!

2023-07-28 07:36 UTC, voelzmo commented on vertical-pod-autoscaler/FAQ.md
> +The VPA cannot only scale the built-in resources like Deployment or StatefulSet, but also Custom Resources which manage
Thanks!

2023-07-28 07:38 UTC, Shubham82 commented
It looks good to me.
/lgtm

2023-08-04 10:42 UTC, mwielgus approved these changes
/lgtm
/approve

2023-08-04 10:46 UTC, merged