add note for CRD and RBAC handling for VPA (>=0.15.0)
kubernetes/autoscaler pull request #6098
Opened 2023-09-10 14:29 UTC by wu0407

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
This pull request addresses the need to update the Custom Resource Definition (CRD) and Role-Based Access Control (RBAC) configuration to support Vertical Pod Autoscaler (VPA) versions 0.15.0 and above. Additionally, it provides guidance on rolling back to version (<=0.14.0) if necessary.

#### Which issue(s) this PR fixes:

Fixes #5921 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-09-12 06:22 UTC, Shubham82 requested changes

2023-09-12 06:22 UTC, Shubham82 commented on vertical-pod-autoscaler/README.md
> +**NOTE:** In version 0.15.0, we have updated the CRD definition and added RBAC for the status resource. If you are upgrading from version (<=0.14.0), you must update the CRD definition and RBAC.
```suggestion
**NOTE:** In version 0.15.0, we have updated the CRD definition and added RBAC for the
status resource. If you are upgrading from version (<=0.14.0), you must update the CRD
definition and RBAC.
```

2023-09-12 06:22 UTC, Shubham82 commented on vertical-pod-autoscaler/README.md
> +If you need to rollback to version (<=0.14.0), please checkout the release for your rollback version and execute ./hack/vpa-up.sh. For example, to rollback to 0.14.0:
```suggestion
If you need to rollback to version (<=0.14.0), please checkout the release for your
rollback version and execute ./hack/vpa-up.sh. For example, to rollback to 0.14.0:
```

2023-09-12 06:23 UTC, Shubham82 commented on vertical-pod-autoscaler/README.md
> +**NOTE:** In version 0.15.0, we have updated the CRD definition and added RBAC for the status resource. If you are upgrading from version (<=0.14.0), you must update the CRD definition and RBAC.
@wu0407 it looks good to me. 
Just small nit: Wrap the line

2023-09-12 06:23 UTC, Shubham82 commented on vertical-pod-autoscaler/README.md
> +If you need to rollback to version (<=0.14.0), please checkout the release for your rollback version and execute ./hack/vpa-up.sh. For example, to rollback to 0.14.0:
nit: Wrap the line

2023-09-12 07:31 UTC, jbartosik reviewed
Thank you. Did you test the update procedure(s)?

2023-10-20 19:38 UTC, sophieliu15 commented
> > Thank you. Did you test the update procedure(s)?
> 
> Sorry, I tested now and Modified the correct execution command. But found the duplicate install `vpa-recommender` in `recommender-deployment` and `recommender-externalmetrics-deployment`. I think needs to be fixed first.
> 
> https://github.com/kubernetes/autoscaler/blob/8e984d7c1a87740f43aa03b3cac00b2247c9e37c/vertical-pod-autoscaler/hack/vpa-process-yamls.sh#L43
> 
> 
> Lally Singh

Hope to follow up on this comment. Was the duplication fixed? If not, could you create an Issue for fixing this and add a comment in this PR to indicate it is blocked by the issue? Thank you!

2023-11-02 14:54 UTC, wu0407 commented
> > > Thank you. Did you test the update procedure(s)?
> > 
> > 
> > Sorry, I tested now and Modified the correct execution command. But found the duplicate install `vpa-recommender` in `recommender-deployment` and `recommender-externalmetrics-deployment`. I think needs to be fixed first.
> > https://github.com/kubernetes/autoscaler/blob/8e984d7c1a87740f43aa03b3cac00b2247c9e37c/vertical-pod-autoscaler/hack/vpa-process-yamls.sh#L43
> > 
> > Lally Singh
> 
> Hope to follow up on this comment. Was the duplication fixed? If not, could you create an Issue for fixing this and add a comment in this PR to indicate it is blocked by the issue? Thank you!

That is fixed by  https://github.com/kubernetes/autoscaler/pull/6151.
The current release version is 1.0.0. so need to update the version in this PR.

2023-11-09 19:20 UTC, kwiesmueller commented
/lgtm
/approve

2023-11-09 19:22 UTC, merged