feat: each node pool can now have different init configs
kubernetes/autoscaler pull request #6184
Opened 2023-10-10 17:24 UTC by Silvest89

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Currently the Hetzner provider is very lacking and the autoscaler does not know beforehand which custom taints/labels the provided node pools have.
This PR adds support for a each nodepool to have their own (currently breaking change, but will see if I have the time to make it backwards compatible). It also supports multi arch node pools. 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
```release-note
Currently this PR introduces a breaking change. However if required I can refactor it so it is backwards compatible
```

2023-10-11 05:19 UTC, Shubham82 commented
Hi @Silvest89 
Please sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

2023-10-11 05:21 UTC, Shubham82 commented
To check EasyCLA

/easycla

2023-10-11 05:25 UTC, Silvest89 commented
Alright, just signed it :)

2023-10-12 08:09 UTC, apricote requested changes
Looks very nice :100: 

Two things I would like to see before approving this:

**Backwards compatibility**: We do not want to break users of the older options, so please add `HCLOUD_CLOUD_INIT` & `HCLOUD_IMAGE` back in. If one of the old options as well as a the `HCLOUD_CLUSTER_CONFIG` is defined, I think we should use the newer options.

**Docs**: It would be great if you can provide an example of how this can be used and how they relate to the older options.

2023-10-12 11:16 UTC, Silvest89 commented
> Looks very nice 💯
> 
> Two things I would like to see before approving this:
> 
> **Backwards compatibility**: We do not want to break users of the older options, so please add `HCLOUD_CLOUD_INIT` & `HCLOUD_IMAGE` back in. If one of the old options as well as a the `HCLOUD_CLUSTER_CONFIG` is defined, I think we should use the newer options.
> 
> **Docs**: It would be great if you can provide an example of how this can be used and how they relate to the older options.

Alright I will be on it. Will update the PR later this week. With updated docs as well :)

2023-10-12 19:36 UTC, Silvest89 commented
@apricote 
Backwards compatibility and updated docs has been implemented

2023-10-17 06:21 UTC, apricote requested changes
Looking good besides one missed error handling and the linting errors from CI :) 

https://github.com/kubernetes/autoscaler/actions/runs/6500103013/job/17654801323?pr=6184#step:6:152

2023-10-17 06:21 UTC, apricote commented on cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go
> +				klog.Fatalf("No node config present for node id `%s` error: %v", spec.name, err)
```suggestion
				klog.Fatalf("No node config present for node group id `%s` error: %v", spec.name, err)
```

2023-10-17 06:21 UTC, apricote commented on cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
> +		json.Unmarshal([]byte(string(clusterConfigEnv)), &clusterConfig)
`clusterConfigEnv` already is a `[]byte`, so no need to convert to string and back to `[]byte`. https://pkg.go.dev/encoding/base64#Encoding.DecodeString

```suggestion
		json.Unmarshal(clusterConfigEnv, &clusterConfig)
```

---

Also please add error handling for failed `json.Unmarshal()`.

2023-10-17 06:21 UTC, apricote commented on cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
> +		UserData:         string(cloudInit),
`cloudInit` is already a string

```suggestion
		UserData:         cloudInit,
```

2023-10-18 10:27 UTC, Silvest89 commented
@apricote 
I've pushed your suggestions! :) Should be alright now

2023-10-20 05:44 UTC, apricote commented
/lgtm
/approve

2023-10-20 05:48 UTC, merged

2023-10-28 10:02 UTC, bgervan commented
Am I seeing correctly that it is not included in the latest version yet?

2023-10-30 09:13 UTC, Shubham82 commented
yes, @bgervan these changes weren't include in the latest version yet i.e. CA v1.28. This feature will be available in CA v1.29.