Deprecate unused node-autoprovisioning-enabled and max-autoprovisione…
kubernetes/autoscaler pull request #6246
Opened 2023-11-03 19:22 UTC by prashantrewar

…d-node-group-count flags

#### What type of PR is this?
/kind bug
/kind deprecation

#### What this PR does / why we need it:
deprecating unused flags
#### Which issue(s) this PR fixes:

Fixes # 
#6228 
#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-11-10 20:25 UTC, towca commented
/assign @towca

2023-11-16 15:24 UTC, towca requested changes

2023-12-09 08:28 UTC, prashantrewar commented on cluster-autoscaler/core/test/common.go
> -	if !context.AutoscalingOptions.NodeAutoprovisioningEnabled {
Done!

2023-12-14 16:20 UTC, towca commented
/lgtm
/approve

2023-12-14 16:20 UTC, towca approved these changes

2023-12-14 16:26 UTC, merged