Add retry for creatingAzureManager in case of throttled requests
kubernetes/autoscaler pull request #6550
Opened 2024-02-20 23:31 UTC by gandhipr

added retry for forceRefresh in case of throttled requests

#### What type of PR is this?
feature

#### What this PR does / why we need it:
added retry for forceRefresh in case of throttled requests

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-03-12 18:54 UTC, rakechill commented on cluster-autoscaler/cloudprovider/azure/azure_manager.go
> +	retryBackoff := wait.Backoff{
how were these values decided?

2024-03-12 19:41 UTC, rakechill approved these changes

2024-03-21 23:50 UTC, tallaxes requested changes

2024-03-21 23:50 UTC, tallaxes commented on cluster-autoscaler/cloudprovider/azure/azure_manager.go
>  	if err := manager.forceRefresh(); err != nil {
No reason to keep this outer `if`?

2024-03-28 15:56 UTC, gandhipr commented on cluster-autoscaler/cloudprovider/azure/azure_manager.go
>  	if err := manager.forceRefresh(); err != nil {
simplified the logic

2024-04-04 19:36 UTC, tallaxes approved these changes

2024-04-17 18:48 UTC, jackfrancis commented
/test pull-cluster-autoscaler-e2e-azure

2024-04-17 21:27 UTC, jackfrancis commented
/retest

2024-04-17 23:08 UTC, jackfrancis approved these changes
/lgtm
/approve

2024-04-17 23:12 UTC, merged