Allow to override rancher provider settings
kubernetes/autoscaler pull request #6606
Opened 2024-03-10 15:38 UTC by k0da

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Currently it is only possible to set provider settings over yaml file.

This commit introduces env variables to override URL, token and cluster name.

If particular environment variable is set it overrides value supplied in yaml file.
#### Which issue(s) this PR fixes
#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
```release-note
Allow to override rancher provider setting via environment variables (`RANCHER_TOKEN`, `RANCHER_URL`, `RANCHER_CLUSTER_NAME`)
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-03-10 15:45 UTC, k0da commented
/retest

2024-03-11 10:47 UTC, donovanmuller requested changes

2024-03-11 10:47 UTC, donovanmuller commented on cluster-autoscaler/cloudprovider/rancher/README.md
> +### config override
```suggestion
### Configuration via environment variables
```

2024-03-11 10:47 UTC, donovanmuller commented on cluster-autoscaler/cloudprovider/rancher/README.md
> + - RANCHER_CLUSER_NAME
```suggestion
 - RANCHER_CLUSTER_NAME
```

2024-03-15 12:38 UTC, mwielgus approved these changes
/lgtm
/approve

2024-03-15 12:42 UTC, merged