NR-250703: cluster-autoscaler improvements for GCP
kubernetes/autoscaler pull request #6739
Opened 2024-04-19 18:39 UTC by sachin-shankar

Add support for label(similar to tags in Azure) based auto-discovery of GCP Managed Instance Groups. The discovery includes figuring out the min and max sizes for the mig pool via labels as well.

Add unit-tests for all the new code added.

Add GCP auto-discovery documentation.

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-04-19 22:58 UTC, Bryce-Soghigian commented on cluster-autoscaler/Makefile
> +REGISTRY?=cf-registry.nr-ops.net/container-fabric
?!!

2024-04-26 15:17 UTC, x13n requested changes

2024-04-26 15:17 UTC, x13n commented on cluster-autoscaler/cloudprovider/gce/gce_manager.go
> +			if c.Labels != nil {
Why is this an error?

2024-04-26 15:17 UTC, x13n commented on cluster-autoscaler/cloudprovider/gce/gce_manager.go
> +		c, err := parseMIGAutoDiscoverySpec(spec)
nit, optional: I think you could simplify the error handling here a bit by first determining the discoverer per spec and then comparing discoverer counts.

2024-04-26 15:17 UTC, x13n commented on cluster-autoscaler/cloudprovider/gce/gce_manager.go
> +	if scaleToZeroSupported {
nit: This is a const that has been set to true for past 7 years, I highly doubt we'll stop supporting scale to 0 at this point.

2024-04-26 15:17 UTC, x13n commented on cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
> +func TestFetchAutoMigsWithMatchingLabelsInInstanceTemplates(t *testing.T) {
Can you make these tests table-based?

2024-04-26 15:17 UTC, x13n commented on cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
> +func TestParseMIGAutoDiscoverySpec(t *testing.T) {
Why is this (and the following 2 tests) not simply a part of `TestParseMIGAutoDiscoverySpecs`?

2024-06-06 08:52 UTC, x13n commented
This doesn't seem to be worked on, so closing for now. @sachin-shankar Please reopen when you have the time to follow up. 

/close

2024-06-06 08:52 UTC, closed without merging