Refactor to format VPA Updater log more efficiently
kubernetes/autoscaler pull request #6883
Opened 2024-05-29 15:35 UTC by nikimanoledaki

#### What type of PR is this?

Follow up to https://github.com/kubernetes/autoscaler/pull/6723

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-05-30 06:22 UTC, Shubham82 commented
/ok-to-test

2024-06-05 10:27 UTC, nikimanoledaki commented
Hi @kwiesmueller 👋  Added the refactor from the previous PR, let me know if it needs any changes, thank you! :)

2024-06-05 11:55 UTC, kwiesmueller requested changes
Thanks! Just a few nits.

2024-06-05 11:55 UTC, kwiesmueller commented on vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
> +		fmt.Fprintf(sb, "%s: ", cr.ContainerName)
Could this just be a
WriteString(name)
WriteString(: )
?

2024-06-05 11:55 UTC, kwiesmueller commented on vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
> -			sb.WriteString("target: ")
I think the WriteString here was already the most efficient way.

2024-06-05 11:55 UTC, kwiesmueller commented on vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
> +				fmt.Fprintf(sb, "%dk ", cr.Target.Memory().ScaledValue(resource.Kilo))
I think what I meant with my original command was that directly calling strconv.Format functions might be more efficient. Maybe that's over optimizing.
Up to you.

2024-06-05 11:55 UTC, kwiesmueller commented on vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
> +			fmt.Fprintf(sb, "uncappedTarget: ")
Same here, I think this can just be WriteString or without f.

2024-06-05 11:55 UTC, kwiesmueller commented on vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
> +		fmt.Fprintf(sb, "\n")
Same here, I think this can be a write string or write rune

2024-09-04 05:41 UTC, Shubham82 commented
Hi @nikimanoledaki, Are you working on this PR, If yes then update this PR as per the changes suggested by @kwiesmueller

2024-09-04 05:41 UTC, Shubham82 commented
/remove-lifecycle stale

2024-11-06 19:45 UTC, adrianmoisey commented
/lgtm cancel

2025-02-04 10:37 UTC, voelzmo commented
Couldn't add commits to your branch, @nikimanoledaki, so I opened https://github.com/kubernetes/autoscaler/pull/7802 to replace this.

/close

2025-02-04 10:37 UTC, closed without merging