Expose new /metrics endpoint to allow monitoring of addon-resizer
kubernetes/autoscaler pull request #6916
Opened 2024-06-11 20:43 UTC by raywainman

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds Prometheus metrics to addon-resizer, allowing monitoring of overall health. Initial implementation adds a single metric called `addon_resizer_execution_outcome` which is a simple counter metric that tracks the outcome of every addon-resizer loop (for example, whether addon-resizer actually updated the deployment for metrics-server).

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Follow up to https://github.com/kubernetes/autoscaler/pull/6764 where addon-resizer is made compatible to run in the control plane.

#### Does this PR introduce a user-facing change?

```release-note
-Expose new `/metrics` endpoint in addon-resizer to expose health metrics that are useful for monitoring purposes.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

To use:
- Ensure the `expose-metrics` flag is set to `true`.
- The `/metrics` endpoint is available by default on port `:8945` (configurable by the `address` flag).

2024-06-12 19:34 UTC, chelseychen commented
LGTM, thanks for the change!

2024-06-14 15:07 UTC, kwiesmueller requested changes

2024-06-14 15:07 UTC, kwiesmueller commented on addon-resizer/nanny/metrics/metrics.go
> +		klog.Fatalf("Failed to start metrics: %v", err)
```suggestion
		klog.Fatalf("Failed to serve metrics: %v", err)
```
Nit: But as this also happens when for some reason the server stops later serve might be more accurate in those cases.

2024-06-14 15:07 UTC, kwiesmueller commented on addon-resizer/nanny/main/pod_nanny.go
> +	metrics.Register()
Is the order of Initialize and Register relevant? I thought register comes first (does Prometheus do registration at runtime?).
Might be worth having a test to see if the metric is served.

2024-06-14 15:08 UTC, kwiesmueller commented
/lgtm
/hold
In case you want to respond to the comments. I don't think they are blocking (even though a test would be nice, but addon-manager doesn't have too many). Feel free to remove the hold if ack.

2024-06-14 17:42 UTC, kwiesmueller approved these changes
/lgtm
/approve

2024-06-18 13:08 UTC, merged