Refactor logging statements in recommender:checkpoint,input
kubernetes/autoscaler pull request #7290
Opened 2024-09-17 08:05 UTC by omerap12

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
To align the logging with the best practices and guidelines established within the Kubernetes ecosystem.

#### Which issue(s) this PR fixes:

As part of https://github.com/kubernetes/autoscaler/issues/6905, I'm splitting this into multiple PRs rather than submitting a single large PR.

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

2024-09-17 09:40 UTC, adrianmoisey commented
/ok-to-test

2024-09-17 09:43 UTC, adrianmoisey commented on vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_source.go
> +					klog.V(4).InfoS("External Metrics Query for VPA: No items","vpa", klog.KRef(vpa.ID.Namespace, vpa.ID.VpaName),"resource", resourceName,"metric", metricName)
Style:
```suggestion
					klog.V(4).InfoS("External Metrics Query for VPA: No items", "vpa", klog.KRef(vpa.ID.Namespace, vpa.ID.VpaName), "resource", resourceName, "metric", metricName)
```

2024-09-17 09:44 UTC, adrianmoisey commented on vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_source.go
> +				klog.V(4).InfoS("External Metrics Query for VPA","vpa", klog.KRef(vpa.ID.Namespace, vpa.ID.VpaName),"resource", resourceName,"metric", metricName,"itemCount", len(m.Items),"firstItem", m.Items[0]
Style:
```suggestion
				klog.V(4).InfoS("External Metrics Query for VPA", "vpa", klog.KRef(vpa.ID.Namespace, vpa.ID.VpaName), "resource", resourceName, "metric", metricName, "itemCount", len(m.Items), "firstItem", m.Items[0])
```

2024-09-17 09:57 UTC, omerap12 commented on vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_source.go
> +					klog.V(4).InfoS("External Metrics Query for VPA: No items","vpa", klog.KRef(vpa.ID.Namespace, vpa.ID.VpaName),"resource", resourceName,"metric", metricName)
yeap

2024-09-17 09:58 UTC, omerap12 commented
@adrianmoisey fixed, do you want me to rebase?

2024-09-17 10:00 UTC, adrianmoisey commented
> @adrianmoisey fixed, do you want me to rebase?

Nah, I think it's fine.

2024-09-24 17:01 UTC, kwiesmueller requested changes

2024-09-24 17:01 UTC, kwiesmueller commented on vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
> +			klog.V(3).InfoS("Loading VPA checkpoint", "namespace", checkpoint.ObjectMeta.Namespace, "VPA", checkpoint.Spec.VPAObjectName, "container", checkpoint.Spec.ContainerName)
nit: consistency with other log lines where it's lowercase vpa
```suggestion
			klog.V(3).InfoS("Loading VPA checkpoint", "namespace", checkpoint.ObjectMeta.Namespace, "vpa", checkpoint.Spec.VPAObjectName, "container", checkpoint.Spec.ContainerName)
```

2024-10-08 11:12 UTC, omerap12 commented
> @omerap12 can you address the remaining comments here?

Of course, I will adjust the code later

2024-10-08 18:43 UTC, omerap12 commented
adjusted @adrianmoisey

2024-10-10 09:23 UTC, adrianmoisey commented
/lgtm

2024-10-18 07:53 UTC, voelzmo requested changes
This is a great change, thanks for the adaptations! Some small comments where we can simplify the logs.

Also: there's a few occasions of `klog.Warnf`, could you also take care of those, while we're at it? Thanks!

2024-10-18 07:53 UTC, voelzmo commented on vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go
> +				klog.ErrorS(err, "Cannot save VPA checkpoint", "namespace", vpa.ID.Namespace, "vpa", vpaCheckpoint.Spec.VPAObjectName, "container", vpaCheckpoint.Spec.ContainerName)
Let's simplify with `klog.KRef` and make clear that the reference is pointing to the VPA, not the checkpoint

```suggestion
				klog.ErrorS(err, "Cannot save checkpoint for VPA", klog.KRef(vpa.ID.Namespace, vpaCheckpoint.Spec.VPAObjectName), "container", vpaCheckpoint.Spec.ContainerName)
```

2024-10-18 07:53 UTC, voelzmo commented on vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go
> +				klog.V(3).InfoS("Saved VPA checkpoint", "namespace", vpa.ID.Namespace, "vpa", vpaCheckpoint.Spec.VPAObjectName, "container", vpaCheckpoint.Spec.ContainerName)
same here

```suggestion
				klog.V(3).InfoS("Saved checkpoint for VPA", klog.KRef(vpa.ID.Namespace, vpaCheckpoint.Spec.VPAObjectName), "container", vpaCheckpoint.Spec.ContainerName)
```

2024-10-18 07:53 UTC, voelzmo commented on vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
> +			klog.V(1).InfoS("An attempt to watch eviction events finished", "waiting", waitTime)
```suggestion
			klog.V(1).InfoS("An attempt to watch eviction events finished", "waitTime", waitTime)
```

2024-10-18 07:53 UTC, voelzmo commented on vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
> +			klog.V(3).InfoS("Loading VPA checkpoint", "namespace", checkpoint.ObjectMeta.Namespace, "vpa", checkpoint.Spec.VPAObjectName, "container", checkpoint.Spec.ContainerName)
same here.

```suggestion
			klog.V(3).InfoS("Loading checkpoint for VPA", klog.KRef(checkpoint.ObjectMeta.Namespace, checkpoint.Spec.VPAObjectName), "container", checkpoint.Spec.ContainerName)
```

2024-10-18 07:53 UTC, voelzmo commented on vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
> +					klog.V(3).InfoS("Orphaned VPA checkpoint cleanup - deleting", "namespace", namespace, "checkpoint", checkpoint.Name)
```suggestion
					klog.V(3).InfoS("Orphaned VPA checkpoint cleanup - deleting", klog.KRef(namespace, checkpoint.Name))
```

2024-10-18 07:53 UTC, voelzmo commented on vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
> +					klog.ErrorS(err, "Orphaned VPA checkpoint cleanup - error deleting", "namespace", namespace, "checkpoint", checkpoint.Name)
```suggestion
					klog.ErrorS(err, "Orphaned VPA checkpoint cleanup - error deleting", klog.KRef(namespace, checkpoint.Name))
```

2024-10-18 07:53 UTC, voelzmo commented on vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
> +			klog.V(6).InfoS("Ignoring vpaCRD in namespace as namespace is ignored", "vpaCRD", klog.KObj(vpaCRD), "namespace", vpaCRD.Namespace)
namespace is already part of the VPA object, we can simplify here

```suggestion
			klog.V(6).InfoS("Ignoring vpaCRD as this namespace is ignored", "vpaCRD", klog.KObj(vpaCRD))
```

2024-10-18 08:18 UTC, voelzmo commented
/unassign @jbartosik

2024-10-18 08:18 UTC, voelzmo commented
/assign
/unassign @kgolab

2024-10-18 13:10 UTC, omerap12 commented
> This is a great change, thanks for the adaptations! Some small comments where we can simplify the logs.
> 
> Also: there's a few occasions of `klog.Warningf`, could you also take care of those, while we're at it? Thanks!

Thanks for your review! Ill just pinned [this](https://github.com/kubernetes/autoscaler/pull/7294#issuecomment-2422423460) ( no need to discuss things twice 😄 )

2024-10-22 07:29 UTC, voelzmo commented
/lgtm
/approve

Thanks!

2024-10-22 07:30 UTC, merged