expand docs for ProvisioningRequest
kubernetes/autoscaler pull request #7297
Opened 2024-09-20 05:31 UTC by grosser

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
- instructions were missing the crd
- was unclear who needs to api flag
- had no examples how the request actually works

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

cc @yaroslava-serdiuk

2024-09-20 09:25 UTC, Shubham82 requested changes

2024-09-20 09:25 UTC, Shubham82 commented on cluster-autoscaler/FAQ.md
> +5. Deploy the [ProvisioningRequest CRD](apis/config/crd/autoscaling.x-k8s.io_provisioningrequests.yaml)
```suggestion
5. Deploy the [ProvisioningRequest CRD](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/apis/config/crd/autoscaling.x-k8s.io_provisioningrequests.yaml)
```

2024-09-20 09:25 UTC, Shubham82 commented on cluster-autoscaler/FAQ.md
> +5. Deploy the [ProvisioningRequest CRD](apis/config/crd/autoscaling.x-k8s.io_provisioningrequests.yaml)
@grosser, PR looks good to me, Just one update link the full URL to it.

2024-09-20 09:25 UTC, Shubham82 commented
/ok-to-test

2024-09-20 12:36 UTC, yaroslava-serdiuk commented
Thanks for your change! 
/lgtm

2024-09-23 04:37 UTC, Shubham82 commented
Thanks @grosser
/lgtm

2024-10-10 06:41 UTC, Shubham82 commented
cc @x13n
could you please approve this PR, so that it will merge?

Thanks!

2024-10-11 08:26 UTC, x13n commented
/approve

2024-10-11 08:28 UTC, merged