Updates Golang version to 1.23
kubernetes/autoscaler pull request #7318
Opened 2024-10-01 17:04 UTC by retornam

Updates Golang version to 1.23

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

It updates the Go version from 1.22 to 1.23

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

None

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None

```docs

```

2024-10-01 17:17 UTC, jackfrancis commented
/test pull-cluster-autoscaler-e2e-azure-master

2024-10-01 19:25 UTC, Shubham82 requested changes

2024-10-01 19:25 UTC, Shubham82 commented on .github/workflows/ci.yaml
> +          go-version: '>=1.23.0'
```suggestion
          go-version: '1.23.0'
```

2024-10-01 19:25 UTC, Shubham82 commented on .github/workflows/ci.yaml
> +          go-version: '>=1.23.0'
Bump Go version to v1.23 to match the k8s/k8s repo.
https://github.com/kubernetes/kubernetes/blob/master/.go-version

2024-10-01 19:25 UTC, Shubham82 commented on builder/Dockerfile
> +FROM golang:1.23.1
```suggestion
FROM golang:1.23.0
```

2024-10-01 19:25 UTC, Shubham82 commented on cluster-autoscaler/go.mod
> +toolchain go1.23.1
```suggestion
toolchain go1.23.0
```

2024-10-01 19:26 UTC, Shubham82 commented
/ok-to-test

2024-10-01 23:57 UTC, retornam commented
@Shubham82  I think I need the `/approve` comment so this can be merged. Thanks

2024-10-02 06:46 UTC, adrianmoisey commented
> @Shubham82 I think I need the `/approve` comment so this can be merged. Thanks

Only users in this list can do an /approve: https://github.com/kubernetes/autoscaler/blob/f79e8d44162a9696ab856af6473d25534baf71b7/OWNERS#L2-L4

2024-10-02 07:26 UTC, Shubham82 commented
@retornam, I have only the right to review and give the LGTM label on PR, once the PR gets the LGTM label then it can be approved by the approvers of the CA directory.

https://github.com/kubernetes/autoscaler/blob/f79e8d44162a9696ab856af6473d25534baf71b7/cluster-autoscaler/OWNERS

2024-10-08 19:08 UTC, Shubham82 commented
cc @MaciekPytel 
PTAL!

2024-10-23 03:18 UTC, Shubham82 commented
/lgtm

2024-10-23 13:38 UTC, Shubham82 commented
cc @MaciekPytel, @gjtempleton
could you please approve this PR.

2024-11-20 12:26 UTC, Shubham82 commented
Hi @gjtempleton @MaciekPytel 
Need your approval to merge this PR.

PTAL!

2025-03-24 09:17 UTC, Shubham82 commented
closing this PR, as PR #7725 is opened for the same.

2025-03-24 09:17 UTC, Shubham82 commented
/close

2025-03-24 09:17 UTC, closed without merging