CA: node readiness err is distinct from node group
kubernetes/autoscaler pull request #7424
Opened 2024-10-22 23:56 UTC by jackfrancis

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR warns if node readiness is not able to be determined, whether or not node group association is detected.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-10-23 13:08 UTC, Shubham82 commented
@jackfrancis, The test case `Tests / test-and-verify (pull_request)` is failed which is mandatory to pass to merge the PR.
Please address it.

2024-10-23 13:15 UTC, Shubham82 commented
It gives the following error:  Readiness for node group ng1 is not found.

you have to update the following `TestRemoveFixNodeTargetSize`  test case under the static_autoscaler_test.go file

https://github.com/kubernetes/autoscaler/blob/1603c19e62dc46a9bb1d176624e1964d974b3ef1/cluster-autoscaler/core/static_autoscaler_test.go#L2162

2024-10-26 08:46 UTC, RobertKielty requested changes
@jackfrancis I like this change! The failure you capture here is in getting _node_ readiness so could we make that super explicit in the warning message?

`klog.Warningf("Failed to get node readiness info for %s: %v", node.Name, errReady)`

2025-01-24 09:47 UTC, Shubham82 commented
/remove-lifecycle stale

2025-06-24 22:04 UTC, closed without merging