Change default lease name for vpa-recommender to "vpa-recommender-lease"
kubernetes/autoscaler pull request #7498
Opened 2024-11-14 16:24 UTC by raywainman

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Changes the default lease name for the vpa-recommender to `vpa-recommender-lease` as this can sometimes conflict with managed deployments of HPA and VPA. See #7461.

Though changing the default here is possibly disruptive during upgrade, we believe it is the right path forward to avoid future outages. See the discussion in #7461 where we also discuss the possible scenarios during upgrade where there could temporarily be two leaders.

#### Which issue(s) this PR fixes:

#7461

#### Does this PR introduce a user-facing change?

```release-note
- Changes the default vpa-recommender leader election lease name to `vpa-recommender-lease`. This CAN result in a situation where VPA would temporarily have two leaders during an upgrade operation. This should be harmless as the two VPA leaders would theoretically be writing the same recommendations. See #7461.
```

2024-11-14 16:30 UTC, raywainman commented
/assign @adrianmoisey 
/assign @voelzmo 
/assign @kwiesmueller

2024-11-14 17:24 UTC, adrianmoisey commented
/lgtm

2024-11-14 17:26 UTC, adrianmoisey commented
Oh, https://github.com/kubernetes/autoscaler/blob/59aefbcd5e95c90530559038ae1d58fdde5381ea/vertical-pod-autoscaler/deploy/vpa-rbac.yaml#L412-L413 also needs updating

2024-11-14 17:47 UTC, omerap12 requested changes
https://github.com/kubernetes/autoscaler/pull/7498#issuecomment-2477011981

To remove the lgtm label

2024-11-14 17:48 UTC, omerap12 commented
/lgtm cancel

2024-11-14 17:49 UTC, omerap12 commented
/assign @raywainman

2024-12-02 10:54 UTC, adrianmoisey commented
@raywainman just a ping to remind you about this
I'm also happy to take it over if you don't have capacity

2024-12-02 19:32 UTC, adrianmoisey commented
/lgtm 

> I will work on the Helm PR separately from this one as well, it is formally setting the flag name in the Helm Chart so is actually a bit of a separate problem from this PR.

Which Helm PR are you referring to?

2024-12-03 08:27 UTC, voelzmo commented
I guess it is this one: https://github.com/cowboysysop/charts/pull/781

The main point is: we can just merge this change, adjusting the default value for the lease and there is no dependency for the helm chart PR, as it always sets the lease name explicitly.

/approve

2024-12-03 08:29 UTC, merged

2024-12-03 08:40 UTC, adrianmoisey commented
> as it always sets the lease name explicitly.

The Helm chart doesn't set it explicitly, they're all commented out.

However, we should try get that PR merged before we cut a release.