VPA: Remove v1beta2
kubernetes/autoscaler pull request #7629
Opened 2024-12-19 05:24 UTC by adrianmoisey

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Remove v1beta2 API

#### Which issue(s) this PR fixes:

Fixes #5922

#### Special notes for your reviewer:

I'm unsure if there is anything else that needs to happen to remove this API

#### Does this PR introduce a user-facing change?

```release-note
Remove deprecated v1beta2 APIs
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2025-01-07 09:45 UTC, voelzmo requested changes
Hey @adrianmoisey thanks for doing this PR! I love changes which consist basically only of removing lines!

I have two asks before this is ready to be merged from my point of view:
* I think we should add a comment to the README similar to what we did for the migration from v1beta1 to v1beta2. Contrary to the previous api migration, there aren't any changes necessary for users (v1 didn't make any incompatible changes), except for changing `v1beta2` to `v1` in their VPA objects.
  * People can find out if they need to to anything by looking at the recommender metrics, e.g. `sum(vpa_recommender_vpa_objects_count) by (api)`
* There seems to be an unused `redis.yaml` and `redis_deprecated.yaml` in the `examples` folder, and they still use `v1beta2`. I think we should also remove those two. Or are those used in a weird test setup somewhere?

2025-01-07 13:43 UTC, adrianmoisey commented
> * I think we should add a comment to the README similar to what we did for the migration from v1beta1 to v1beta2. Contrary to the previous api migration, there aren't any changes necessary for users (v1 didn't make any incompatible changes), except for changing `v1beta2` to `v1` in their VPA objects.
>   
>   * People can find out if they need to to anything by looking at the recommender metrics, e.g. `sum(vpa_recommender_vpa_objects_count) by (api)`

Yup, good call out here. Done in a193b1af68f135254691c910aa21a65a247605d2

> * There seems to be an unused `redis.yaml` and `redis_deprecated.yaml` in the `examples` folder, and they still use `v1beta2`. I think we should also remove those two. Or are those used in a weird test setup somewhere?

This is a little bit of a a strange one. These aren't for v1beta2, they're for v1beta1.
From what I can tell, they are referenced in the [MIGRATE.md](https://github.com/kubernetes/autoscaler/blob/a587c552af2d0ba08202af00b4f46b9988465f98/vertical-pod-autoscaler/MIGRATE.md) file.

I was considering deleting the YAML files and the README, but I imagine that someone on an old (ancient?) version may need those instructions to migrate. Additionally, the MIGRATE.md file is quite out of date (ie: it doesn't mention v1)

I'm unsure if we should leave them as is, and remove them all in the future. Or just delete them all now, as they are in git history.

Thoughts?

2025-01-08 13:52 UTC, voelzmo commented
> This is a little bit of a a strange one. These aren't for v1beta2, they're for v1beta1.
From what I can tell, they are referenced in the [MIGRATE.md](https://github.com/kubernetes/autoscaler/blob/a587c552af2d0ba08202af00b4f46b9988465f98/vertical-pod-autoscaler/MIGRATE.md) file.

I didn't find references to the `redis.yaml` file there, but only references to the `hamster_deprecated.yaml` – I think we can safely remove it. I'm also fine to leave them in there, don't want to block this PR on that decision.

/approve

2025-01-08 17:12 UTC, liggitt commented on vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
> -  - name: v1beta2
what ensures all existing persisted data in v1beta2 format is migrated to the new storage format? is there a reason to remove this rather than switching it to `served:false` by default?

2025-01-08 19:27 UTC, adrianmoisey commented on vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
> -  - name: v1beta2
I'm not too sure really. I had a look at what was done with v1beta1, and since it wasn't listed here, I assumed it just needed to be deleted.
Is there a best practice that we can follow to remove APIs?

2025-01-09 10:03 UTC, voelzmo commented on vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
> -  - name: v1beta2
Hey @liggitt, thanks for jumping in here!

> what ensures all existing persisted data in v1beta2 format is migrated to the new storage format

Just to elaborate on our thought process:
v1beta2 has `storage: false` since vpa release 0.10.0, which happened 5 years ago: https://github.com/kubernetes/autoscaler/commit/99a4a7a66f58939c37a52b7092b57e261d5b9d93

Technically, I guess you're right that it could happen that people still have VPAs from 5 years ago in their clusters. In the previous occasion which @adrianmoisey mentioned, the onus was put on the user to do this: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/MIGRATE.md#notice-on-switching-to-v1beta2-version-03x-to-040

We can also just set `served: false` and continue with this path, as you suggested.

2025-01-09 17:09 UTC, liggitt commented on vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
> -  - name: v1beta2
> v1beta2 has storage: false since [vpa release 0.10.0](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.10.0), which happened 3 years ago: https://github.com/kubernetes/autoscaler/commit/99a4a7a66f58939c37a52b7092b57e261d5b9d93

unless something always automatically writes to all existing VPA objects, just the passage of time doesn't guarantee existing objects have been touched / updated

I would start by just setting `served: false`, since that ensures you won't break existing persisted data.

I also don't really know how user-facing this API is... consumers of this API who have users still writing manifests against v1beta2 would consider dropping serving of it a breaking change, and might not be able to consume updates any more... starting with `served: false` gives them a trivial way to switch back to `served: true` and start more active outreach / migration of their users

2025-01-10 19:26 UTC, adrianmoisey commented on vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
> -  - name: v1beta2
I've made the change as you've suggested.

> I would start by just setting served: false, since that ensures you won't break existing persisted data.


What is the next step? How do we go about removing APIs? Is there a doc somewhere I can read up on this?

2025-01-14 06:45 UTC, adrianmoisey commented
/milestone vertical-pod-autoscaler-1.3.0

2025-01-14 12:28 UTC, voelzmo approved these changes
/approve

2025-01-15 09:13 UTC, voelzmo commented
@liggitt do you think we can merge this with the recent modifications that @adrianmoisey did?

2025-01-16 21:13 UTC, liggitt commented
Just stopping serving them is a way safer step, and can be reversed by consumers of the CRD by toggling the boolean back to `served: true`

I don't know how you communicate out changes in the CRD to consumers, but a clearer release note indicating v1beta2 is no longer *served* but can still be read from etcd would probably be good

2025-01-20 15:27 UTC, raywainman commented
/lgtm

We'll make sure to clearly document this for the 1.3.0 release, thanks all.

2025-01-20 15:28 UTC, merged